[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/chat-config"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/rooms/*"
  to = "/.netlify/functions/rooms"
  status = 200

[[redirects]]
  from = "/api/email/*"
  to = "/.netlify/functions/email"
  status = 200

[[redirects]]
  from = "/api/email-links/*"
  to = "/.netlify/functions/email"
  status = 200

[[redirects]]
  from = "/api/security/*"
  to = "/.netlify/functions/email"
  status = 200

[[redirects]]
  from = "/api/tasks/*/email-links"
  to = "/.netlify/functions/email"
  status = 200

[[redirects]]
  from = "/api/translate/*"
  to = "/.netlify/functions/email"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
